[tool.tartufo]
repo-path = "."
cleanup = true
regex = true
entropy = true
exclude-paths = ".tartufo-excludes"
exclude-signatures = [
    # Kubernetes SHA_256 && MD5
    "2a54b5d2d6bd9fafc0b04cda89d9cfbfc8bf46d44b3479ac9507c6e9d67aadac",
    "0d74049d6e6f3fa7df5d2b4e2d00666594e6ba5d95965ff1a54fc2a97103035f",
    "158b7fad70c571b346b92f6da8344aecd336b07b3e739cca87b3ef500cd242b1",
    "216a8a76e2b374aef0161842df103596fbdec35a6c8f7d06ec1ba68d2154c411",
    "21a6f44745032efa375e46d5c33e614ae755e021dd915a9858237f2479ac1877",
    "2acd768f911d53f8c31a87d8488f5e243ba3d5daf113d4fab17af87dec7a891e",
    "2f38344b3b013f922db1769c74de48b405aeadeebd0aa230729b960018392440",
    "3777babeed4092fc9c1196ff2e77f1745ce8a715d2cb34334ba3cc3c9c8d6547",
    "38e71eee3b76c64a93ae509b04509933e7734e1266dbc474ce87d0428e178353",
    "474242e5b16f0130e7f83e21b0120f4847a7f9bc34e0d0690d63347edd0d2c2e",
    "727ff50666905542e20439be1f27809dfda55490ff541187f6e2a5320df2215c",
    "82d57b73f65efb39b4ed77a41c1cf3524d95e8835715c88a11e6f3fd34251a56",
    "a28c1b4ba066b61da2c97229cac67acb35cdb8f0f4e613601a5531f44f4a4dc8",
    "a5aad4d04a5b531056d476058776f538af0d3d5d6b0675c3e0492ec0e6966b9f",
    "af73ed88570d89ef8cae6b2eec6935ecaa6b5607c9403295e31be2b279395835",
    "b67e5d1cd5d01da4e170637d11d0813525bbf2fd36bc924e2fecc3c724e7678d",
    "e2bf38db437ad8100373a6f217bab632cd7f0fa44e7f2f1157e752671c5d1a69",
    "e673ded437d184914b5febb349d3a1ab658e8bd11b273e1bbd5fa8f1c7b8a86b",
    "1aacf98a2d29e1fbfb40bc5f5290c96f30a571d1ab2fe5d2481fdfd0c66a29e5"
]
